Repository ojasaklechayt/Reslink-Dashboard, pull requests merged in 2023-10, with the labels that each got.

#3 add basic instructions to `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#5 update : contributor.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#8 Update: README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#10 Fix: mobile view search-bar
  README.md
  dashboard/src/components/dashboard/dashboard.jsx
  dashboard/src/components/sidebar/sidebar.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#15 fix: add link to Reslink icon, add dashboard favicon, change site title
  dashboard/index.html
  dashboard/public/dashboard.svg
  dashboard/public/vite.svg
  dashboard/src/components/sidebar/sidebar.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#19 Added functional notifications menu component
  dashboard/src/components/dashboard/Notifications.jsx
  dashboard/src/components/dashboard/dashboard.jsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#20 Fixed responsiveness of notifications drop down menu
  dashboard/src/components/dashboard/Notifications.jsx
Labels: bug, enhancement, hacktoberfest-accepted, hacktoberfest

#21 changes in background UI
  dashboard/src/components/sidebar/sidebar.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#22 [feat] [UI] improve search button ui
  dashboard/src/components/dashboard/dashboard.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#28 Close #27: Design enhancement for dashboard cards/widgets
  dashboard/src/components/dashboard/dashboard.jsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#24 Close #23: Responsive design enhancement -> top navbar
  dashboard/src/components/dashboard/Notifications.jsx
  dashboard/src/components/dashboard/dashboard.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#26 Close #25: Design improvement for sidebar
  dashboard/src/components/sidebar/sidebar.jsx
Labels: hacktoberfest-accepted, hacktoberfest
